### ISSUE TITLE
Wireguard support?

### ISSUE THREAD

**Issue by t-e-s-tweb** [dyhkwong/Exclave#1]
Any plans to add wireguard support? For using with CF warp for improving privacy and security.

**Comment by MuzammilCEO** [comment]
Hello,

There are several errors while compiling the code, could you please give an idea which OS is best for development of SagerNet? I tried on macOS, Ubuntu and Windows. Also tried to run the action workflows but the results were very similar. 
Your assistance will be appreciated.
