### ISSUE TITLE
连接测速问题

### ISSUE THREAD

**Issue by kafeixiang** [dyhkwong/Exclave#17]
批量测延迟时全是不可用状态，其实节点是可用的，这种情况出现在服务器为域名的节点上
[SagerNet 8710951300566229091.log](https://github.com/dyhkwong/SagerNet/files/15092985/SagerNet.8710951300566229091.log)

**Comment by yqk100** [comment]
> V2Ray 的 DNS 解析问题是个屎山，建议直连 DNS 使用系统 DNS 或带 `+local://` 的 DNS。

创建ss节点加密方式为none情况下密码选项不能为空，会报错。
失败；infra/conf/serial: failed to parse jsonconfig infra/conf/v4: Shadowsocks password is not specified.

**Comment by jhli999** [comment]
导入vpn的wireguard用url连接测试的时候会崩溃闪退，直连dns改成https+local://223.5.5.5/dns-query就不会崩溃闪退了

**Comment by jhli999** [comment]
> > 导入vpn的wireguard用url连接测试的时候会崩溃闪退，直连dns改成https+local://223.5.5.5/dns-query就不会崩溃闪退
> 
> 提供一下日志，目前只能发现 panic: close of closed channel，我没有用 wireguard 进行测试。

[
[SagerNet 7900243802240603078.log](https://github.com/user-attachments/files/15899448/SagerNet.7900243802240603078.log)
](url)

**Comment by jhli999** [comment]
> > 导入vpn的wireguard用url连接测试的时候会崩溃闪退，直连dns改成https+local://223.5.5.5/dns-query就不会崩溃闪退
> 
> 提供一下日志，目前只能发现 panic: close of closed channel，我没有用 wireguard 进行测试。

[Uploading SagerNet 8594893537592524267.log…]()

**Comment by jhli999** [comment]
> > 导入vpn的wireguard用url连接测试的时候会崩溃闪退，直连dns改成https+local://223.5.5.5/dns-query就不会崩溃闪退
> 
> 提供一下日志，目前只能发现 panic: close of closed channel，我没有用 wireguard 进行测试。

[SagerNet 8594893537592524267.log](https://github.com/user-attachments/files/15899988/SagerNet.8594893537592524267.log)

**Comment by jhli999** [comment]
> WireGuard 是由 Xray 的实现，Xray 那至少有三个 WireGuard`panic: close of closed channel`的问题，不过那边的“管理员”好像完全没看出来 关闭 投诉，把这个推到别的原因上去 (:
把直连dns tcp://223.5.5.5改成https+local://223.5.5.5/dns-query就不闪退了

**Comment by jhli999** [comment]
> > WireGuard 由 Xray 的实现，Xray 那至少有三个 WireGuard`panic: close of closed channel`的问题，不过那边的“管理员”好像完全没看出来关闭投诉，把这个推到别的原因上去（:
> > 把直连 dns tcp://223.5.5.5改成https+local://223.5.5.5/dns-query就不闪退了

0.10.12不用改直连dns也不闪退了
