### ISSUE TITLE
TODO: Change app name and logo

### ISSUE THREAD

**Issue by dyhkwong** [dyhkwong/Exclave#46]

**Comment by jhli999** [comment]
支持

**Comment by jhli999** [comment]
改好没有

**Comment by jhli999** [comment]
0.11不错不错

**Comment by InvisibleRain** [comment]
It may also be a good idea to [unfork](https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks) the repository through a support ticket, so that Exclave becomes visible when searching on GitHub.

**Comment by ManjulaSB550** [comment]
Please add NTP client setting for provided time instead of the system time
