### ISSUE TITLE
URL 测试 闪退

### ISSUE THREAD

**Issue by kafeixiang** [dyhkwong/Exclave#58]
URI测试 闪退 原版也有这个问题

**Comment by adcdefghijk** [comment]
> 这个日志还是没有有效信息。如果有其他人可以复现的可以在这里发一下。

hy2 url測試閃退
[Exclave.8859131633909565640.log](https://github.com/user-attachments/files/16621503/Exclave.8859131633909565640.log)

**Comment by adcdefghijk** [comment]
> > 这个日志还是没有有效信息。如果有其他人可以复现的可以在这里发一下。
> 
> hy2 url测试闪退 [Exclave.8859131633909565640.log](https://github.com/user-attachments/files/16621503/Exclave.8859131633909565640.log)

附上節點以供測試百分百閃退更換dns也是
[profiles_hy.txt](https://github.com/user-attachments/files/16621525/profiles_hy.txt)

**Comment by adcdefghijk** [comment]
> > hy2 url測試闪退
> 
> hy2 的大概知道什么问题，是快速的作者故意留下的坑，但解释不了为什么非 hy2 也闪退 (:
虎兕跟nekobox沒有闪退测试速度也快准确性也好点

**Comment by adcdefghijk** [comment]
好长时间没遇到url测试闪退了，除非里面有hy2节点而且是节点多时可能闪退
