### ISSUE TITLE
不情之请：一键更新所有订阅和Cloudflare Warp 生成配置，谢谢

### ISSUE THREAD

**Issue by Git230919** [dyhkwong/Exclave#92]
感谢作者为大家提供一款这么便捷易用的工具，相信不少人都是从NB转过来的用户，所以不情之请，不知能否吸纳NB一些不错的功能，比如分组界面增加 一键更新所有订阅 ，工具界面增加Cloudflare Warp 生成配置（这个真的很好用啊，尤其做链代），再次感谢

**Comment by adcdefghijk** [comment]
支持支持

**Comment by Git230919** [comment]
> 一键更新所有订阅：现在 NDK 或者 Go 有点 bug #51，该问题解决之前不会去推进。
> 
> 生成 Cloudflare Warp 配置我拒绝实现。

谢谢解答
